#!/usr/bin/env python3
"""
TestNodeFragments.py

Regression test LOCKING IN the containerField fix released in x3d.py 4.0.65.5,
and the HAnimHumanoid version-attribute requirement added in 4.0.65.6 beta.

    https://sourceforge.net/p/x3d/tickets/117/
    Python-SAI issue #2 -- XML serializer omits containerField for nodes in a
    non-default field (HAnim skeleton, PBR/unlit textures)

    python3 TestNodeFragments.py        # exit 0 = pass, 1 = regression

STATUS BY RELEASE

    4.0.65.3       fails 1, 3, 3b, 4     (pre-fix behaviour)
    4.0.65.5       fails 4               (containerField fixed)
    4.0.65.6 beta  ALL PASS              (version attribute now required)

WHAT IT COVERS

  1. PhysicalMaterial + baseTexture. An ImageTexture in the `baseTexture` slot
     must serialize with containerField='baseTexture'. Without it the texture
     reparses into the default `texture` slot, which PhysicalMaterial does not
     define, and the surface renders untextured with no error anywhere.

  2. CONTROL -- the default slot must NOT carry containerField. Canonical X3D
     omits an attribute equal to its default. This proves the fix is slot-aware
     rather than blanket, so a later change cannot regress into emitting
     containerField everywhere.

  3. HAnimHumanoid skeleton/segments -- containerField on non-default node
     fields, and DEF ordered before USE.

  3b. ComposedCubeMapTexture -- the hardest instance of this defect in the
     object model: SIX children, all the same element type (ImageTexture), each
     in a DIFFERENT named field, and NO default slot at all. Without
     containerField the six faces are indistinguishable and the cube map cannot
     be reconstructed. Case contributed by John Carlson (ballx_ite.py in
     coderextreme/X3DJSONLD).

  4. HAnimHumanoid.version is serialized. This one was originally reported as a
     serializer defect; it was not. version='2.0' equalled the default and was
     therefore correctly omitted. Don Brutzman resolved it at the SPECIFICATION
     level instead -- the attribute is now required in the X3D XML Schema and
     DOCTYPE, with only '2.0' (approved) and '2.1' (draft) permitted for X3D4 --
     so the check now passes for the right reason. Legacy HAnim models suffered
     from versionitis inconsistencies; this closes that.

A NOTE ON VERSIONS, corrected by Don Brutzman: X3D and X3DUOM are entirely
backwards compatible across versions, with no breaks in functionality, which is
why ONE x3d.py serves every X3D model (3.0 through draft 4.1). Independent
X3DUOM files are maintained per version, each autogenerated from the
corresponding XML Schema and each a superset of the last. Field names here are
therefore the current ones (frontTexture, not front) because the object model
grew, not because compatibility was broken.

Alexander Hoffman, 2026-08-04. Verified against 4.0.65.3, 4.0.65.5 and
4.0.65.6 beta.
Don Brutzman, 2026-08-03. Renamed for clarity to match functionality, entered
into version control as a regression test.

Most recent version maintained at
https://sourceforge.net/p/x3d/code/HEAD/tree/www.web3d.org/x3d/stylesheets/python/examples/TestNodeFragments.py
"""
import re
import sys

from x3d import x3d as X

VERSION = 2
FAILURES = []


def check(label, ok, expected, actual):
    print(f"  [{'PASS' if ok else 'FAIL'}] {label}")
    if not ok:
        print(f"         expected: {expected}")
        print(f"         actual  : {actual}")
        FAILURES.append(label)


def main():
    # x3d.py prints its own package version banner on import, so this line
    # reports the X3D DOCUMENT version the package defaults to -- a different
    # thing, and worth not conflating.
    print(f"TestNodeFragments v{VERSION} -- default X3D document version: "
          f"{X.X3D().version}\n")

    # --- 1. non-default slot: baseTexture ---------------------------------
    app = X.Appearance(material=X.PhysicalMaterial(
        DEF="brick", baseTexture=X.ImageTexture(DEF="btex", url=["brick.png"])))
    xml = app.XML()
    print("  --- PhysicalMaterial with baseTexture ---")
    for line in xml.splitlines():
        print("  " + line)
    check("ImageTexture in `baseTexture` carries containerField='baseTexture'",
          "containerField='baseTexture'" in xml,
          "<ImageTexture ... containerField='baseTexture'/>",
          "no containerField -- reparses into `texture`, which "
          "PhysicalMaterial does not define; the surface renders untextured")

    # --- 2. control: the DEFAULT slot must stay bare -----------------------
    bare = X.Appearance(texture=X.ImageTexture(DEF="t2", url=["b.png"])).XML()
    check("control: default `texture` slot emits NO containerField",
          "containerField" not in bare,
          "<ImageTexture DEF='t2' url='\"b.png\"'/>", bare.strip())

    # --- 3. HAnim non-default node fields ---------------------------------
    h = X.HAnimHumanoid(DEF="hanim_Test", name="Test", version="2.0")
    h.skeleton = [X.HAnimJoint(DEF="hanim_humanoid_root", name="humanoid_root")]
    h.skeleton[0].children = [X.HAnimSegment(DEF="hanim_sacrum", name="sacrum")]
    h.segments = [X.HAnimSegment(USE="hanim_sacrum")]
    hx = h.XML()
    print("\n  --- HAnimHumanoid ---")
    for line in hx.splitlines():
        print("  " + line)
    check("HAnimJoint in `skeleton` carries containerField='skeleton'",
          "containerField='skeleton'" in hx, "containerField='skeleton'",
          "absent -- the joint reparses into `children` and the skeleton "
          "stops being a skeleton")
    check("HAnimSegment in `segments` carries containerField='segments'",
          "containerField='segments'" in hx, "containerField='segments'",
          "absent")

    i_def, i_use = hx.find("DEF='hanim_sacrum'"), hx.find("USE='hanim_sacrum'")
    check("DEF precedes USE in document order",
          -1 < i_def < i_use, "the DEF node serializes first",
          f"DEF at {i_def}, USE at {i_use} -- USE is a forward reference")

    # --- 3b. six non-default slots, no default at all ----------------------
    FACES = ["backTexture", "bottomTexture", "frontTexture",
             "leftTexture", "rightTexture", "topTexture"]
    cube = X.ComposedCubeMapTexture(DEF="cube", **{
        f: X.ImageTexture(url=["%s.png" % f[0]]) for f in FACES})
    cx = cube.XML()
    print("\n  --- ComposedCubeMapTexture (6 faces) ---")
    for line in cx.splitlines():
        print("  " + line)
    got = sorted(re.findall(r"containerField='(\w+)'", cx))
    check("all six cube-map faces carry their containerField",
          got == sorted(FACES),
          "one containerField per face: " + ", ".join(sorted(FACES)),
          ("emitted " + (", ".join(got) if got else "NONE")) +
          " -- without them the six faces are indistinguishable and the cube "
          "map cannot be reconstructed")

    # --- 4. version attribute, required as of 4.0.65.6 ---------------------
    check("HAnimHumanoid.version='2.0' is serialized",
          "version=" in hx, "<HAnimHumanoid ... version='2.0'>",
          f"absent from XML although the object holds "
          f"{getattr(h, 'version', None)!r} -- required since 4.0.65.6")

    print()
    if FAILURES:
        print(f"FAILED ({len(FAILURES)}): " + "; ".join(FAILURES))
        return 1
    print("All checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
