#!/usr/bin/env python3
"""Generate techne/profiles.py — the profile/component tables, from the spec.

Technē's catalog is hand-authored craft-knowledge. This table is NOT: X3D already
publishes, per profile, exactly which nodes it admits, and per node, which
component and level it belongs to. The x3d_mcp server surfaces both
(`list_profiles`, `describe_node`). So we transcribe rather than invent — the same
move as the BAML mirror: a deterministic, dependency-free Python copy of a
canonical declaration.

    cd techne && ../.venv/bin/python gen_profiles.py > techne/profiles.py
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import sys

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

REPO = "/Users/alexander/x3d_mcp"
PY = f"{REPO}/.venv/bin/python"


async def gather() -> tuple[dict[str, list[str]], dict[str, list]]:
    params = StdioServerParameters(
        command=PY, args=["-m", "src.server", "--cwd", REPO],
        cwd=REPO, env={**os.environ})
    async with stdio_client(params) as (r, w):
        async with ClientSession(r, w) as s:
            await s.initialize()

            async def call(tool: str, **a) -> str:
                res = await s.call_tool(tool, a)
                return "\n".join(c.text for c in res.content
                                 if getattr(c, "type", "") == "text")

            # profile -> the nodes it admits. The list lives in the profile's
            # appinfo prose: "Allowed X3D nodes for this profile are: A B C."
            profiles_raw = json.loads(await call("list_profiles"))
            profiles: dict[str, list[str]] = {}
            for name, body in profiles_raw.items():
                m = re.search(r"Allowed X3D nodes for this profile are:\s*(.+?)\.",
                              body.get("appinfo", ""), re.S)
                nodes = sorted(set(m.group(1).split())) if m else []
                profiles[name] = nodes

            # node -> (component, level)
            nodes_raw = json.loads(await call("list_nodes"))
            all_nodes = nodes_raw if isinstance(nodes_raw, list) else \
                sorted({n for v in nodes_raw.values() for n in v}) \
                if isinstance(nodes_raw, dict) else []
            comp: dict[str, list] = {}
            for nt in all_nodes:
                try:
                    d = json.loads(await call("describe_node", node_type=nt))
                except Exception:
                    continue
                c, lv = d.get("component"), d.get("level")
                if c and lv is not None:
                    comp[nt] = [c, int(lv)]
            return profiles, comp


def main() -> None:
    profiles, comp = asyncio.run(gather())

    # The Full profile admits everything; the server's appinfo may not enumerate
    # it. Treat an empty/absent Full as "all nodes".
    if not profiles.get("Full"):
        profiles["Full"] = sorted(comp)

    out = sys.stdout
    out.write('"""Profile/component tables — GENERATED by gen_profiles.py. Do not edit.\n\n')
    out.write("Transcribed from the X3D spec as the x3d_mcp server reports it\n")
    out.write("(`list_profiles` for the per-profile node sets, `describe_node` for each\n")
    out.write("node's component and level). Regenerate when the server's X3D version moves.\n")
    out.write('"""\n')
    out.write("from __future__ import annotations\n\n")

    out.write("# profile -> the node types it admits\n")
    out.write("PROFILE_NODES: dict[str, frozenset[str]] = {\n")
    for p in ("Core", "Interchange", "Interactive", "Immersive", "MedicalInterchange",
              "CADInterchange", "Full"):
        if p not in profiles:
            continue
        out.write(f"    {p!r}: frozenset({sorted(profiles[p])!r}),\n")
    out.write("}\n\n")

    out.write("# node type -> (component, level) it requires\n")
    out.write("NODE_COMPONENT: dict[str, tuple[str, int]] = {\n")
    for n in sorted(comp):
        c, lv = comp[n]
        out.write(f"    {n!r}: ({c!r}, {lv}),\n")
    out.write("}\n\n")

    out.write('''
# The highest level each component is known to reach. Used to declare a component
# generously: an under-declared level silently drops nodes (the failure we are
# here to prevent), while an over-declared level is always legal and merely
# admits more than the scene uses. The server's per-node level metadata is not
# entirely trustworthy -- it reports EnvironmentLight, an X3D 4.0 addition, as
# Lighting level 1 -- so we do not lean on it for the level, only for the
# component NAME, which is the load-bearing part.
COMPONENT_MAX_LEVEL: dict[str, int] = {}
for _n, (_c, _l) in NODE_COMPONENT.items():
    COMPONENT_MAX_LEVEL[_c] = max(COMPONENT_MAX_LEVEL.get(_c, 0), _l)


def missing_components(node_types, profile: str) -> list[tuple[str, int]]:
    """Which <component> declarations a scene needs, given the nodes it uses.

    A node outside the declared profile is NOT fixed by raising the profile.
    Measured against X_ITE 11.6.6 with a minimal HAnim figure:

        Interchange + <component name='HAnim' level='1'/>  -> RENDERS
        Immersive   without the component                  -> VANISHES
        Full        without the component                  -> RENDERS

    Only the Full profile admits HAnim implicitly. The component declaration is
    the fix; the profile is not -- and "Immersive" sounding like it covers
    everything is exactly the trap.

    Returns (component, level) pairs to declare.
    """
    admitted = PROFILE_NODES.get(profile, frozenset())
    if profile == "Full":
        return []
    need: set[str] = set()
    for nt in node_types:
        if nt in admitted:
            continue
        cl = NODE_COMPONENT.get(nt)
        if cl:
            need.add(cl[0])
    return sorted((c, COMPONENT_MAX_LEVEL.get(c, 1)) for c in need)
''')


if __name__ == "__main__":
    main()
